Update README.md
modmail-dev/logviewer pull request #57
Opened 2022-09-02 16:14 UTC by lidistat67

Add log viewer self-hosting guide made by @lorenzo132.

2022-09-02 20:23 UTC, Taaku18 requested changes
There are also a few changes I'd like made to the external guide apart from the review change(s) @lorenzo132:

- Specify the system requirements at the top, i.e. mention that the guide is for Ubuntu 20.04-22.04 (this range is just my speculation, use the actual compatible releases)
- You don't need the extra `logviewer` at the end of `git clone https://github.com/kyb3r/logviewer`
- Add a section to install the appropriate Python Version (Python 3.9)
- Don't install pipenv through apt, AFAIK it's discouraged. Either install through pip, or use the [convenience script](https://pipenv.pypa.io/en/latest/install/#crude-installation-of-pipenv): `curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python` (and since we're using `curl`, we need `sudo apt install curl` as well)
- Don't use `sudo` for any pipenv commands
- To start the logviewer, we provide a custom command `pipenv run logviewer`, although both ways are the same, using the abstract "logviewer" instead of the actual command provides more flexibility 
- Installing npm through apt is also highly discouraged, it's recommended to use nvm, which can be installed using the official [convenience scripts](https://github.com/nvm-sh/nvm#install--update-script), or the [commands suggested](https://yoember.com/nodejs/the-best-way-to-install-node-js-with-yarn/#on-linux) by [pm2](https://pm2.keymetrics.io/docs/usage/quick-start/)
  - I also suggest adding info on systemd, which requires less overhead while accomplishing the same task
- The nginx template is missing a few proxy fields, such as setting the Host and X-Real-IP headers
  - Also add `/static` caching directive to the nginx conf file

Everything else LGTM.

2022-09-02 20:23 UTC, Taaku18 commented on README.md
> +Below are some general instructions to help you get started on a Linux machine. The [installation guide](https://localhosting-logviewer.logs.vodka/) will guide you through the entire installation pro
```suggestion
Below are some general instructions to help you get started on a Linux machine. Alternatively, you can checkout [@lorenzo132](https://github.com/lorenzo132)'s [**logviewer guide**](https://localhosting-logviewer.logs.vodka/) which contains an in-depth walk through of the entire logviewer setup process on Ubuntu 20.04.
```
IMO, calling it "installation guide" might be confusing since that's the name we refer to the main Modmail setup guide. Moreover, the wordings could be changed to improve the flow of the section.

2022-09-03 21:07 UTC, lorenzo132 commented on README.md
> +Below are some general instructions to help you get started on a Linux machine. The [installation guide](https://localhosting-logviewer.logs.vodka/) will guide you through the entire installation pro
* You don't need the extra logviewer at the end of git clone https://github.com/kyb3r/logviewer ( this is required since i wrote the tutorial into having a specific `logviewer` folder )

* Don't use sudo for any pipenv commands ( this is required for some services/some hosting providers require it as they dont give root )

* Installing npm through apt is also highly discouraged, it's recommended to use nvm, which can be installed using the official convenience scripts, or the commands suggested by pm2 ( nvm is less userfriendly )

* The nginx template is missing a few proxy fields, such as setting the Host and X-Real-IP headers
Also add /static caching directive to the nginx conf file ( adding this does not have a single usecase besides some extra logging which should not be needed to keep user privacy safe and clear )

* Don't install pipenv through apt, AFAIK it's discouraged. Either install through pip, or use the convenience script: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python (and since we're using curl, we also need sudo apt install curl) (This can be added if your *really* insist on it, besides that both apt install and curling the link u provided itll do the same thing, just curl again, is less userfriendly. )

* Add a section to install the appropriate Python Version (Python 3.9) (can be done, however ubuntu 20.04 comes standard with python 3.8.2 and Ubuntu comes standard with 3.10.4. Both python versions are stable and working with both logviewer and modmail.

* To start the logviewer, we provide a custom command pipenv run logviewer, although both ways are the same, using the abstract "logviewer" instead of the actual command provides more flexibility in case we change the startup command ( In case of the event of the starting command changing the file will be changed before it reaches the master branch )

2022-09-03 23:25 UTC, Taaku18 commented on README.md
> +Below are some general instructions to help you get started on a Linux machine. The [installation guide](https://localhosting-logviewer.logs.vodka/) will guide you through the entire installation pro
> this is required since i wrote the tutorial into having a specific logviewer folder

The default folder for git clone is the name of the repository. Ergo, you don't need to explicitly specify.

> this is required for some services/some hosting providers require it as they dont give root

I mentioned to not use sudo for pipenv, I never referred to any services that requires root (e.g. apt, nginx). The reasons being in twofold: 
- Python and the logviewer code itself doesn't require root
- Running the logviewer process in root is a huge security concern. What if we have a security vulnerability that facilitates remote code execution? The attacker would have full access of the host machine. Whereas, running it under an user account (or even better: it's own non-privileged user/group) would only have their user account compromised as opposed to the entire system

TL;DR, pipenv commands don't need root, so no need to use sudo. 

> nvm is less userfriendly

To install node using the recommended method (with nvm), it only boils down to a few commands which you can just copy and paste:
```shell
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm ls-remote | tail -n100 | grep LTS  # optional, find the LTS version of node.js
nvm install 16.17.0  # install, use, set as default
nvm use 16.17.0 
nvm alias default 16.17.0
npm install -g npm  # update npm
```
The reason to use this over apt install is already privately discussed.
Alternatively, installing node through [snap](https://snapcraft.io/node) is fine as well and may simplify the process.

> adding this does not have a single usecase besides some extra logging which should not be needed to keep user privacy safe and clear 

The reason for adding `/static` to nginx is for caching, nginx would be able to effectively cache static contents so to lighten the python server load. And the proxy headers are required to identify originating IP addresses of proxied requests for the web server. Since you provided the file as a template, it shouldn't be any less user friendly for the user to copy and paste.

> This can be added if your really insist on it, besides that both apt install and curling the link u provided itll do the same thing, just curl again, is less userfriendly.

pipenv from apt is not officially supported, it may be out of date. Moreover, running a single command `curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python` shouldn't be much trouble for a non-tech savvy user. I suggested this script as opposed to through pip is so that the user need not worry about installing pip.

> can be done, however ubuntu 20.04 comes standard with python 3.8.2 and Ubuntu comes standard with 3.10.4. Both python versions are stable and working with both logviewer and modmail.

Although the code may support Python 3.8, it is not intended to. The deployment target is 3.9, it's very possible we may add code that's 3.9 specific and would break on other versions. Plus, it shouldn't be much trouble to install 3.9, we can use pyenv, or simply, this command should work fine on Ubuntu 20.04 and 22.04:
```shell
sudo apt update && sudo apt install software-properties-common python3.9 python3-dev python3-pip
```

>  In case of the event of the starting command changing the file will be changed before it reaches the master branch

IMO it's just one less thing to worry about, there's no downside of using `pipenv run logviewer` as opposed to `pipenv run python3 app.py`.

2023-03-15 16:24 UTC, closed without merging